// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicMarket.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicMarket.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924175946_AddSmartAlerts")]
    partial class AddSmartAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicMarket.Api.Models.CatalogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCollectible")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NewPriceLkr")
                        .HasColumnType("numeric");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "Model")
                        .IsUnique();

                    b.ToTable("CatalogModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Yamaha",
                            Category = "Acoustic Guitar",
                            IsCollectible = false,
                            Model = "F310",
                            NewPriceLkr = 48000m,
                            ReleaseYear = 2001,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Yamaha",
                            Category = "Acoustic Guitar",
                            IsCollectible = false,
                            Model = "FG800",
                            NewPriceLkr = 95000m,
                            ReleaseYear = 2016,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Fender",
                            Category = "Acoustic Guitar",
                            IsCollectible = false,
                            Model = "CD-60S",
                            NewPriceLkr = 68000m,
                            ReleaseYear = 2017,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Epiphone",
                            Category = "Acoustic Guitar",
                            IsCollectible = false,
                            Model = "DR-100",
                            NewPriceLkr = 52000m,
                            ReleaseYear = 2010,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Gibson",
                            Category = "Acoustic Guitar",
                            IsCollectible = false,
                            Model = "J-45 Standard",
                            NewPriceLkr = 850000m,
                            ReleaseYear = 2020,
                            Tier = "premium"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Ibanez",
                            Category = "Electric Guitar",
                            IsCollectible = false,
                            Model = "GRX70QA",
                            NewPriceLkr = 65000m,
                            ReleaseYear = 2015,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Ibanez",
                            Category = "Electric Guitar",
                            IsCollectible = false,
                            Model = "RG550 Genesis",
                            NewPriceLkr = 320000m,
                            ReleaseYear = 2018,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Fender",
                            Category = "Electric Guitar",
                            IsCollectible = false,
                            Model = "Player Stratocaster",
                            NewPriceLkr = 265000m,
                            ReleaseYear = 2018,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Epiphone",
                            Category = "Electric Guitar",
                            IsCollectible = false,
                            Model = "Les Paul Standard 60s",
                            NewPriceLkr = 215000m,
                            ReleaseYear = 2020,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Gibson",
                            Category = "Electric Guitar",
                            IsCollectible = false,
                            Model = "Les Paul Standard 50s",
                            NewPriceLkr = 890000m,
                            ReleaseYear = 2019,
                            Tier = "premium"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Gibson",
                            Category = "Electric Guitar",
                            IsCollectible = true,
                            Model = "1959 Les Paul Standard Reissue",
                            NewPriceLkr = 2200000m,
                            ReleaseYear = 1959,
                            Tier = "premium"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Fender",
                            Category = "Electric Guitar",
                            IsCollectible = true,
                            Model = "1965 Stratocaster Relic Reissue",
                            NewPriceLkr = 1450000m,
                            ReleaseYear = 1965,
                            Tier = "premium"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Yamaha",
                            Category = "Bass Guitar",
                            IsCollectible = false,
                            Model = "TRBX174",
                            NewPriceLkr = 78000m,
                            ReleaseYear = 2014,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Ibanez",
                            Category = "Bass Guitar",
                            IsCollectible = false,
                            Model = "SR300E",
                            NewPriceLkr = 135000m,
                            ReleaseYear = 2016,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Fender",
                            Category = "Bass Guitar",
                            IsCollectible = false,
                            Model = "Player Jazz Bass",
                            NewPriceLkr = 285000m,
                            ReleaseYear = 2018,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Casio",
                            Category = "Keyboard",
                            IsCollectible = false,
                            Model = "CT-S300",
                            NewPriceLkr = 55000m,
                            ReleaseYear = 2019,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Yamaha",
                            Category = "Keyboard",
                            IsCollectible = false,
                            Model = "PSR-E373",
                            NewPriceLkr = 82000m,
                            ReleaseYear = 2020,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Roland",
                            Category = "Keyboard",
                            IsCollectible = false,
                            Model = "XPS-10",
                            NewPriceLkr = 220000m,
                            ReleaseYear = 2013,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Roland",
                            Category = "Keyboard",
                            IsCollectible = false,
                            Model = "XPS-30",
                            NewPriceLkr = 340000m,
                            ReleaseYear = 2016,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Korg",
                            Category = "Keyboard",
                            IsCollectible = false,
                            Model = "Kross 2-61",
                            NewPriceLkr = 275000m,
                            ReleaseYear = 2017,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Yamaha",
                            Category = "Keyboard",
                            IsCollectible = false,
                            Model = "Montage 8",
                            NewPriceLkr = 1250000m,
                            ReleaseYear = 2016,
                            Tier = "premium"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Pearl",
                            Category = "Drum Kit",
                            IsCollectible = false,
                            Model = "Roadshow 5-Piece",
                            NewPriceLkr = 210000m,
                            ReleaseYear = 2015,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Tama",
                            Category = "Drum Kit",
                            IsCollectible = false,
                            Model = "Imperialstar 5-Piece",
                            NewPriceLkr = 295000m,
                            ReleaseYear = 2019,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Roland",
                            Category = "Drum Kit",
                            IsCollectible = false,
                            Model = "TD-07KV V-Drums",
                            NewPriceLkr = 380000m,
                            ReleaseYear = 2020,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Pearl",
                            Category = "Drum Kit",
                            IsCollectible = false,
                            Model = "Export EXX",
                            NewPriceLkr = 340000m,
                            ReleaseYear = 2018,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Audio-Technica",
                            Category = "Microphone",
                            IsCollectible = false,
                            Model = "AT2020",
                            NewPriceLkr = 34000m,
                            ReleaseYear = 2004,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Shure",
                            Category = "Microphone",
                            IsCollectible = false,
                            Model = "SM58",
                            NewPriceLkr = 38000m,
                            ReleaseYear = 1966,
                            Tier = "mid"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Shure",
                            Category = "Microphone",
                            IsCollectible = false,
                            Model = "SM7B",
                            NewPriceLkr = 145000m,
                            ReleaseYear = 2001,
                            Tier = "premium"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Boss",
                            Category = "Amplifier",
                            IsCollectible = false,
                            Model = "Katana-50 MkII",
                            NewPriceLkr = 88000m,
                            ReleaseYear = 2019,
                            Tier = "budget"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Marshall",
                            Category = "Amplifier",
                            IsCollectible = false,
                            Model = "DSL40CR",
                            NewPriceLkr = 320000m,
                            ReleaseYear = 2018,
                            Tier = "premium"
                        });
                });

            modelBuilder.Entity("MusicMarket.Api.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiReason")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FairPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FairPriceMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FairPriceMin")
                        .HasColumnType("numeric");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceConfidence")
                        .HasColumnType("text");

                    b.Property<double?>("PriceDeviationPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("PriceExplanation")
                        .HasColumnType("text");

                    b.Property<string>("PriceVerdict")
                        .HasColumnType("text");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SoldPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.ListingImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<string>("PHash")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int?>("ListingId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SavedSearchId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("SavedSearchId");

                    b.HasIndex("UserId", "IsRead");

                    b.HasIndex("UserId", "ListingId", "Type")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.SavedSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Conditions")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelKeyword")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueryText")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("SavedSearches");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("Approval")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NicCardNumber")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShopRegisterId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceWhenSaved")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.Listing", b =>
                {
                    b.HasOne("MusicMarket.Api.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.ListingImage", b =>
                {
                    b.HasOne("MusicMarket.Api.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.Notification", b =>
                {
                    b.HasOne("MusicMarket.Api.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicMarket.Api.Models.SavedSearch", "SavedSearch")
                        .WithMany()
                        .HasForeignKey("SavedSearchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicMarket.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("SavedSearch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.PriceHistory", b =>
                {
                    b.HasOne("MusicMarket.Api.Models.Listing", "Listing")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.SavedSearch", b =>
                {
                    b.HasOne("MusicMarket.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.WishlistItem", b =>
                {
                    b.HasOne("MusicMarket.Api.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicMarket.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicMarket.Api.Models.Listing", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
